-- ============================================================
-- 01_load_data.sql
-- Creates internal stage, uploads CSVs, and loads into RAW tables
-- NOTE: PUT commands require execution via SnowSQL or Python connector.
--       This file documents the logic; actual upload is done by
--       the companion script load_data.py
-- ============================================================

USE WAREHOUSE MARKETING_WH;
USE DATABASE MARKETING_COPILOT;
USE SCHEMA RAW;

-- Stage was created via DDL:
-- CREATE OR REPLACE STAGE MARKETING_STAGE
--   FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

-- COPY INTO statements for all 11 tables:

COPY INTO RAW_CLIENTS FROM @MARKETING_STAGE/clients/
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
  ON_ERROR = 'CONTINUE';

COPY INTO RAW_PRODUCTS FROM @MARKETING_STAGE/products/
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
  ON_ERROR = 'CONTINUE';

COPY INTO RAW_CHANNELS FROM @MARKETING_STAGE/channels/
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
  ON_ERROR = 'CONTINUE';

COPY INTO RAW_AUDIENCE_SEGMENTS FROM @MARKETING_STAGE/audience_segments/
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
  ON_ERROR = 'CONTINUE';

COPY INTO RAW_CUSTOMER_PROFILES FROM @MARKETING_STAGE/customer_profiles/
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
  ON_ERROR = 'CONTINUE';

COPY INTO RAW_CAMPAIGNS FROM @MARKETING_STAGE/campaigns/
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
  ON_ERROR = 'CONTINUE';

COPY INTO RAW_BRIDGE_CAMPAIGN_SEGMENT FROM @MARKETING_STAGE/bridge_campaign_segment/
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
  ON_ERROR = 'CONTINUE';

COPY INTO RAW_CAMPAIGN_METRICS FROM @MARKETING_STAGE/campaign_metrics/
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
  ON_ERROR = 'CONTINUE';

COPY INTO RAW_CUSTOMER_FEEDBACK FROM @MARKETING_STAGE/customer_feedback/
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
  ON_ERROR = 'CONTINUE';

COPY INTO RAW_MARKET_EVENTS FROM @MARKETING_STAGE/market_events/
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
  ON_ERROR = 'CONTINUE';

COPY INTO RAW_BRAND_GUIDELINES FROM @MARKETING_STAGE/brand_guidelines/
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
  ON_ERROR = 'CONTINUE';
