-- ============================================================
-- 01_setup.sql
-- Creates database, schemas, and warehouse for Marketing Co-Pilot
-- ============================================================

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS MARKETING_COPILOT;

CREATE SCHEMA IF NOT EXISTS MARKETING_COPILOT.RAW;
CREATE SCHEMA IF NOT EXISTS MARKETING_COPILOT.STAGING;
CREATE SCHEMA IF NOT EXISTS MARKETING_COPILOT.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS MARKETING_COPILOT.SEMANTIC;

CREATE WAREHOUSE IF NOT EXISTS MARKETING_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE MARKETING_WH;
USE DATABASE MARKETING_COPILOT;
USE SCHEMA RAW;

-- Stages: CSV landing zone, semantic model YAML, Streamlit app files
CREATE STAGE IF NOT EXISTS MARKETING_COPILOT.RAW.MARKETING_STAGE
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);
CREATE STAGE IF NOT EXISTS MARKETING_COPILOT.SEMANTIC.SEMANTIC_STAGE DIRECTORY = (ENABLE = TRUE);
CREATE STAGE IF NOT EXISTS MARKETING_COPILOT.SEMANTIC.STREAMLIT_STAGE DIRECTORY = (ENABLE = TRUE);
