-- ============================================================
-- 01_setup.sql
-- Creates database, schemas, and warehouse for Marketing Co-Pilot
-- ============================================================

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS MARKETING_COPILOT;

CREATE SCHEMA IF NOT EXISTS MARKETING_COPILOT.RAW;
CREATE SCHEMA IF NOT EXISTS MARKETING_COPILOT.STAGING;
CREATE SCHEMA IF NOT EXISTS MARKETING_COPILOT.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS MARKETING_COPILOT.SEMANTIC;

CREATE WAREHOUSE IF NOT EXISTS MARKETING_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE MARKETING_WH;
USE DATABASE MARKETING_COPILOT;
USE SCHEMA RAW;
