-- ============================================================
-- 07_cortex_search.sql
-- Cortex Search services used by the three agents and the MCP server
-- ============================================================

USE WAREHOUSE MARKETING_WH;
USE DATABASE MARKETING_COPILOT;

-- Brand guidelines (110 sections across 12 clients)
CREATE OR REPLACE CORTEX SEARCH SERVICE SEMANTIC.BRAND_SEARCH
  ON GUIDELINE_TEXT
  ATTRIBUTES CLIENT_NAME, SECTION_TITLE
  WAREHOUSE = MARKETING_WH
  TARGET_LAG = '1 hour'
AS
SELECT GUIDELINE_TEXT, CLIENT_NAME, SECTION_TITLE, TONE_KEYWORDS, INDUSTRY, DOS, DONTS, COLOR_PALETTE
FROM ANALYTICS.FACT_BRAND_GUIDELINES;

-- Market events calendar (53 events)
CREATE OR REPLACE CORTEX SEARCH SERVICE SEMANTIC.MARKET_SEARCH
  ON DESCRIPTION
  ATTRIBUTES EVENT_TYPE, REGION, IMPACT_LEVEL
  WAREHOUSE = MARKETING_WH
  TARGET_LAG = '1 hour'
AS
SELECT DESCRIPTION, EVENT_NAME, EVENT_TYPE, REGION, IMPACT_LEVEL, AFFECTED_INDUSTRIES,
       START_DATE::VARCHAR AS START_DATE, END_DATE::VARCHAR AS END_DATE
FROM ANALYTICS.DIM_MARKET_EVENT;

-- News articles loaded by the event intelligence pipeline (src/intelligence)
CREATE OR REPLACE CORTEX SEARCH SERVICE SEMANTIC.EVENT_NEWS_SEARCH
  ON SEARCH_TEXT
  ATTRIBUTES BRAND_NAME, SENTIMENT, ARTICLE_TYPE
  WAREHOUSE = MARKETING_WH
  TARGET_LAG = '1 hour'
AS
SELECT COALESCE(TITLE, '') || ' ' || COALESCE(DESCRIPTION, '') AS SEARCH_TEXT,
       TITLE, BRAND_NAME, SENTIMENT, ARTICLE_TYPE, SOURCE_NAME, URL, RUN_ID
FROM RAW.NEWS_ARTICLES;
